"""Convert FHIR resources into GraphRAG-friendly narrative text."""

from typing import Any, Dict, List

from .fhir_utils import (
    display_code,
    display_code_list,
    get_date,
    observation_value,
    patient_demographics,
    patient_display_name,
)


def _group_resources(resources: List[Dict[str, Any]]) -> Dict[str, List[Dict[str, Any]]]:
    """Group resources by FHIR resourceType."""
    grouped: Dict[str, List[Dict[str, Any]]] = {}
    for resource in resources:
        rt = resource.get("resourceType")
        if not rt:
            continue
        grouped.setdefault(rt, []).append(resource)
    return grouped


def _render_patient_header(patient: Dict[str, Any]) -> List[str]:
    name = patient_display_name(patient)
    demo = patient_demographics(patient)

    lines = [
        f"# Patient Record: {name}",
        "",
        f"{name} is a synthetic patient generated by Synthea in FHIR R4 format.",
        f"{name} has gender {demo['gender']} and was born on {demo['birth_date']}.",
        (
            f"{name} resides in {demo['city']}, {demo['state']}, {demo['country']}."
        ),
        "",
    ]
    return lines


def _render_conditions(name: str, conditions: List[Dict[str, Any]]) -> List[str]:
    if not conditions:
        return []

    lines = ["## Clinical Conditions", ""]
    for c in conditions:
        condition_name = display_code(c.get("code"))
        onset = get_date(c, "onsetDateTime", "recordedDate")
        clinical_status = display_code(c.get("clinicalStatus"))
        lines.append(
            f"{name} has been diagnosed with {condition_name}. "
            f"The condition was recorded on {onset} and has clinical status {clinical_status}."
        )
    lines.append("")
    return lines


def _render_medications(name: str, meds: List[Dict[str, Any]]) -> List[str]:
    if not meds:
        return []

    lines = ["## Medications", ""]
    for m in meds:
        med_name = display_code(m.get("medicationCodeableConcept"))
        status = str(m.get("status") or "unknown")
        authored = get_date(m, "authoredOn")
        lines.append(
            f"{name} was prescribed {med_name}. "
            f"The prescription status is {status}, authored on {authored}."
        )
    lines.append("")
    return lines


def _render_observations(name: str, observations: List[Dict[str, Any]]) -> List[str]:
    if not observations:
        return []

    lines = ["## Observations", ""]
    for o in observations:
        obs_name = display_code(o.get("code"))
        value = observation_value(o)
        effective = get_date(o, "effectiveDateTime", "issued")
        lines.append(
            f"{name} had observation {obs_name} recorded as {value} on {effective}."
        )
    lines.append("")
    return lines


def _render_procedures(name: str, procedures: List[Dict[str, Any]]) -> List[str]:
    if not procedures:
        return []

    lines = ["## Procedures", ""]
    for p in procedures:
        proc_name = display_code(p.get("code"))
        status = str(p.get("status") or "unknown")
        performed = get_date(p, "performedDateTime")
        lines.append(
            f"{name} underwent procedure {proc_name} on {performed}. "
            f"The procedure status is {status}."
        )
    lines.append("")
    return lines


def _render_encounters(name: str, encounters: List[Dict[str, Any]]) -> List[str]:
    if not encounters:
        return []

    lines = ["## Encounters", ""]
    for e in encounters:
        enc_type = display_code_list(e.get("type"))
        status = str(e.get("status") or "unknown")
        start = get_date(e, "period")
        lines.append(
            f"{name} had a healthcare encounter of type {enc_type} on {start}. "
            f"The encounter status is {status}."
        )
    lines.append("")
    return lines


def _render_care_plans(name: str, care_plans: List[Dict[str, Any]]) -> List[str]:
    if not care_plans:
        return []

    lines = ["## Care Plans", ""]
    for cp in care_plans:
        categories = display_code_list(cp.get("category"))
        status = str(cp.get("status") or "unknown")
        lines.append(
            f"{name} is enrolled in a care plan for {categories} with status {status}."
        )
    lines.append("")
    return lines


def _render_allergies(name: str, allergies: List[Dict[str, Any]]) -> List[str]:
    if not allergies:
        return []

    lines = ["## Allergies", ""]
    for a in allergies:
        allergy_name = display_code(a.get("code"))
        clinical_status = display_code(a.get("clinicalStatus"))
        lines.append(
            f"{name} has an allergy to {allergy_name} with clinical status {clinical_status}."
        )
    lines.append("")
    return lines


def _render_immunizations(name: str, immunizations: List[Dict[str, Any]]) -> List[str]:
    if not immunizations:
        return []

    lines = ["## Immunizations", ""]
    for i in immunizations:
        vaccine = display_code(i.get("vaccineCode"))
        occurrence = get_date(i, "occurrenceDateTime")
        lines.append(
            f"{name} received immunization {vaccine} on {occurrence}."
        )
    lines.append("")
    return lines


def _render_relationship_summary(
    name: str,
    conditions: List[Dict[str, Any]],
    meds: List[Dict[str, Any]],
    observations: List[Dict[str, Any]],
) -> List[str]:
    """Emit explicit relationship sentences that help GraphRAG entity linking."""
    if not (conditions or meds or observations):
        return []

    lines = ["## Relationships", ""]

    condition_names = [display_code(c.get("code")) for c in conditions]
    med_names = [display_code(m.get("medicationCodeableConcept")) for m in meds]
    observation_names = [display_code(o.get("code")) for o in observations]

    for condition in condition_names:
        lines.append(f"{name} is associated with the clinical condition {condition}.")

    for med in med_names:
        lines.append(f"{name} is treated with the medication {med}.")

    for obs in observation_names:
        lines.append(f"{name} has clinical measurement {obs}.")

    # Cross-link conditions and medications to encourage graph edges
    for condition in condition_names:
        for med in med_names:
            lines.append(
                f"The medication {med} is administered to a patient with {condition}."
            )

    for condition in condition_names:
        for obs in observation_names:
            lines.append(
                f"The observation {obs} is monitored for a patient with {condition}."
            )

    lines.append("")
    return lines


def build_patient_document(resources: List[Dict[str, Any]]) -> str:
    """Convert one patient's FHIR resources into a narrative document."""
    grouped = _group_resources(resources)

    patients = grouped.get("Patient", [])
    if not patients:
        return ""

    patient = patients[0]
    name = patient_display_name(patient)

    conditions = grouped.get("Condition", [])
    medications = grouped.get("MedicationRequest", [])
    observations = grouped.get("Observation", [])
    procedures = grouped.get("Procedure", [])
    encounters = grouped.get("Encounter", [])
    care_plans = grouped.get("CarePlan", [])
    allergies = grouped.get("AllergyIntolerance", [])
    immunizations = grouped.get("Immunization", [])

    lines: List[str] = []
    lines.extend(_render_patient_header(patient))
    lines.extend(_render_conditions(name, conditions))
    lines.extend(_render_medications(name, medications))
    lines.extend(_render_observations(name, observations))
    lines.extend(_render_procedures(name, procedures))
    lines.extend(_render_encounters(name, encounters))
    lines.extend(_render_care_plans(name, care_plans))
    lines.extend(_render_allergies(name, allergies))
    lines.extend(_render_immunizations(name, immunizations))
    lines.extend(_render_relationship_summary(name, conditions, medications, observations))

    return "\n".join(lines).strip() + "\n"